// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOjYr4Hkrfciplf4rhH_ofvBGwmWar4xM',
    appId: '1:454230831023:web:069b34f8141aabff9a495a',
    messagingSenderId: '454230831023',
    projectId: 'fashion-store-app-a9388',
    authDomain: 'fashion-store-app-a9388.firebaseapp.com',
    storageBucket: 'fashion-store-app-a9388.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2L3erWOu3Gu3rF83uRkC-uo-NrOgv1P0',
    appId: '1:454230831023:android:f436f423c18582229a495a',
    messagingSenderId: '454230831023',
    projectId: 'fashion-store-app-a9388',
    storageBucket: 'fashion-store-app-a9388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBioaHHD3AR0aiNICxOwXwTxXW5hvUc55g',
    appId: '1:454230831023:ios:428bbbf9245797a29a495a',
    messagingSenderId: '454230831023',
    projectId: 'fashion-store-app-a9388',
    storageBucket: 'fashion-store-app-a9388.firebasestorage.app',
    iosBundleId: 'com.example.richFashionPhase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBioaHHD3AR0aiNICxOwXwTxXW5hvUc55g',
    appId: '1:454230831023:ios:428bbbf9245797a29a495a',
    messagingSenderId: '454230831023',
    projectId: 'fashion-store-app-a9388',
    storageBucket: 'fashion-store-app-a9388.firebasestorage.app',
    iosBundleId: 'com.example.richFashionPhase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOjYr4Hkrfciplf4rhH_ofvBGwmWar4xM',
    appId: '1:454230831023:web:24e751fa5fdac0929a495a',
    messagingSenderId: '454230831023',
    projectId: 'fashion-store-app-a9388',
    authDomain: 'fashion-store-app-a9388.firebaseapp.com',
    storageBucket: 'fashion-store-app-a9388.firebasestorage.app',
  );
}
